import Login from "./Login"
import AddPost from "./AddPost"
import AllPosts from "./AllPosts"
import EditPost from "./EditPost"
import Home from "./Home"
import Post from "./Post"
import Signup from "./Signup"